//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.18 at 06:29:58 PM EDT 
//


package org.peace_tools.decagon.jaxb;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 * 	Information about an executable to be run as part of a genomic assembler
 * 	or some other processing step in the pipeline.
 * 			
 * 
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Executable", namespace = "http://www.peace-tools.org/decagon/", propOrder = {
    "fileName",
    "internal",
    "description",
    "detectArgsList",
    "detectOutputCheck",
    "detectExitCode"
})
public class Executable {

    @XmlElement(namespace = "http://www.peace-tools.org/decagon/")
    protected String fileName;
    @XmlElement(namespace = "http://www.peace-tools.org/decagon/")
    protected InternalExeType internal;
    @XmlElement(namespace = "http://www.peace-tools.org/decagon/", required = true)
    protected String description;
    @XmlElement(namespace = "http://www.peace-tools.org/decagon/", required = true)
    protected ArgumentList detectArgsList;
    @XmlElement(namespace = "http://www.peace-tools.org/decagon/")
    protected OutputCheckData detectOutputCheck;
    @XmlElement(namespace = "http://www.peace-tools.org/decagon/", required = true, defaultValue = "0")
    protected BigInteger detectExitCode;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String name;

    /**
     * 
     * 							
     * 	The file-name of the actual executable-file that is associated
     * 	with this entry. The executable name should not include
     * 	any path information. It should simply be the file name of
     * 	the executable. Path information is added as needed by DECAGON
     * 	depending on how the platform on which DECAGON is being run.
     * 	<b>NOTE: For internal executables (when the internal attribute
     * 	is specified in the XML) this element is actually ignored.
     * 							
     * 						
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * Sets the value of the fileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileName(String value) {
        this.fileName = value;
    }

    /**
     * 
     * 	Element to indicate that the executable referred to is an executable that
     * 	is internal to PEACE or DECAGON and is distributed as part of PEACE.
     * 	This element is typically used when running the peace backend clustering/
     * 	assembly engine or when running EAST assembler. This information is
     * 	used to decide on the final path and name of the executable.
     * 						
     * 
     * @return
     *     possible object is
     *     {@link InternalExeType }
     *     
     */
    public InternalExeType getInternal() {
        return internal;
    }

    /**
     * Sets the value of the internal property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternalExeType }
     *     
     */
    public void setInternal(InternalExeType value) {
        this.internal = value;
    }

    /**
     * 
     * 						
     * 	This is a generic description about the executable
     * 	that may be presented to the user to provide additional
     * 	information about the assembler. If this description
     * 	contains HTML presentation tags then they must be 
     * 	represented as corresponding XML entities.
     * 						
     * 					
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * 
     * 						
     * 	This element defines the set of arguments that need to be passed
     * 	to the genomic assembler exectuable to verify that it is operational.
     * 	The arguments are typically set to generate the version information
     * 	about the assembler or provide brief help about the assember. This
     * 	parameter-set is not meant to perform assembly. Instead it is used to
     * 	run the assembler and provide feedback to the user so that the user
     * 	can verify that the assembler is available and is ready for assembly.
     * 						
     * 					
     * 
     * @return
     *     possible object is
     *     {@link ArgumentList }
     *     
     */
    public ArgumentList getDetectArgsList() {
        return detectArgsList;
    }

    /**
     * Sets the value of the detectArgsList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArgumentList }
     *     
     */
    public void setDetectArgsList(ArgumentList value) {
        this.detectArgsList = value;
    }

    /**
     * 
     * 						
     * 	This element can be used to provide additional information to 
     * 	automatically perform some basic verification about the
     * 	expected output from running the process using the arguments in
     * 	detectArgsList element. The value specified here is	treated as a 
     * 	regular expression and not just a simple string to provide additional
     * 	flexibility to perform more robust checks. The output can be from 
     * 	either standard output and/or standard error. 
     * 						
     * 					
     * 
     * @return
     *     possible object is
     *     {@link OutputCheckData }
     *     
     */
    public OutputCheckData getDetectOutputCheck() {
        return detectOutputCheck;
    }

    /**
     * Sets the value of the detectOutputCheck property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutputCheckData }
     *     
     */
    public void setDetectOutputCheck(OutputCheckData value) {
        this.detectOutputCheck = value;
    }

    /**
     * 
     * 						
     * 	The expected exit code from running the command to detect operational
     * 	status of the this executable of some server. Typically the exit
     * 	code from successfully running a command is always zero. However, if
     * 	certain command are expected to provide a non-zero exit code that 
     * 	actually indicates a successful operation, then this value can be
     * 	used to specify a non-zero value.
     * 						
     * 					
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDetectExitCode() {
        return detectExitCode;
    }

    /**
     * Sets the value of the detectExitCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDetectExitCode(BigInteger value) {
        this.detectExitCode = value;
    }

    /**
     * 
     * 	A unique name/identifier used to refer to this executable entry when
     * 	defining processes associated with a given assembly job. The value 
     * 	set for this attribute is also used as the value for the executable
     * 	attribute associated with a process. 
     * 				
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
