//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.18 at 06:29:58 PM EDT 
//


package org.peace_tools.decagon.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for JobKind.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="JobKind">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="serial"/>
 *     &lt;enumeration value="multithreaded"/>
 *     &lt;enumeration value="parallel"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "JobKind", namespace = "http://www.peace-tools.org/decagon/")
@XmlEnum
public enum JobKind {

    @XmlEnumValue("serial")
    SERIAL("serial"),
    @XmlEnumValue("multithreaded")
    MULTITHREADED("multithreaded"),
    @XmlEnumValue("parallel")
    PARALLEL("parallel");
    private final String value;

    JobKind(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static JobKind fromValue(String v) {
        for (JobKind c: JobKind.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
