//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.18 at 06:29:58 PM EDT 
//


package org.peace_tools.decagon.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OutputFileType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OutputFileType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="fasta"/>
 *     &lt;enumeration value="sff"/>
 *     &lt;enumeration value="ace"/>
 *     &lt;enumeration value="sam"/>
 *     &lt;enumeration value="bam"/>
 *     &lt;enumeration value="tsv"/>
 *     &lt;enumeration value="txt"/>
 *     &lt;enumeration value="binary"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "OutputFileType", namespace = "http://www.peace-tools.org/decagon/")
@XmlEnum
public enum OutputFileType {

    @XmlEnumValue("fasta")
    FASTA("fasta"),
    @XmlEnumValue("sff")
    SFF("sff"),
    @XmlEnumValue("ace")
    ACE("ace"),
    @XmlEnumValue("sam")
    SAM("sam"),
    @XmlEnumValue("bam")
    BAM("bam"),
    @XmlEnumValue("tsv")
    TSV("tsv"),
    @XmlEnumValue("txt")
    TXT("txt"),
    @XmlEnumValue("binary")
    BINARY("binary");
    private final String value;

    OutputFileType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OutputFileType fromValue(String v) {
        for (OutputFileType c: OutputFileType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
