//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.18 at 06:29:58 PM EDT 
//


package org.peace_tools.decagon.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.peace_tools.decagon.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ParameterSet_QNAME = new QName("http://www.peace-tools.org/decagon/", "parameterSet");
    private final static QName _AssemblerDetails_QNAME = new QName("http://www.peace-tools.org/decagon/", "assemblerDetails");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.peace_tools.decagon.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link Executable }
     * 
     */
    public Executable createExecutable() {
        return new Executable();
    }

    /**
     * Create an instance of {@link Process }
     * 
     */
    public Process createProcess() {
        return new Process();
    }

    /**
     * Create an instance of {@link OutputFile }
     * 
     */
    public OutputFile createOutputFile() {
        return new OutputFile();
    }

    /**
     * Create an instance of {@link AssemblerDetails }
     * 
     */
    public AssemblerDetails createAssemblerDetails() {
        return new AssemblerDetails();
    }

    /**
     * Create an instance of {@link ResourceFactors }
     * 
     */
    public ResourceFactors createResourceFactors() {
        return new ResourceFactors();
    }

    /**
     * Create an instance of {@link Argument }
     * 
     */
    public Argument createArgument() {
        return new Argument();
    }

    /**
     * Create an instance of {@link Job }
     * 
     */
    public Job createJob() {
        return new Job();
    }

    /**
     * Create an instance of {@link Condition }
     * 
     */
    public Condition createCondition() {
        return new Condition();
    }

    /**
     * Create an instance of {@link ParameterSet }
     * 
     */
    public ParameterSet createParameterSet() {
        return new ParameterSet();
    }

    /**
     * Create an instance of {@link ArgumentList }
     * 
     */
    public ArgumentList createArgumentList() {
        return new ArgumentList();
    }

    /**
     * Create an instance of {@link OutputCheckData }
     * 
     */
    public OutputCheckData createOutputCheckData() {
        return new OutputCheckData();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParameterSet }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.peace-tools.org/decagon/", name = "parameterSet")
    public JAXBElement<ParameterSet> createParameterSet(ParameterSet value) {
        return new JAXBElement<ParameterSet>(_ParameterSet_QNAME, ParameterSet.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AssemblerDetails }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.peace-tools.org/decagon/", name = "assemblerDetails")
    public JAXBElement<AssemblerDetails> createAssemblerDetails(AssemblerDetails value) {
        return new JAXBElement<AssemblerDetails>(_AssemblerDetails_QNAME, AssemblerDetails.class, null, value);
    }

}
